### ISSUE TITLE
Metrics problem

### ISSUE THREAD

**Issue by netwaze** [Supporterino/truenas-graphite-to-prometheus#32]
Hi,
I just tested your project and everything is really great :) 
however, I notice that some metrics do not come up like cpu_frequency, cpu_throttling, zfs_l2_size and disk_qops (only for sdb). 
I don't think I made a mistake with the installation because everything else works perfectly.
My Truenas version is Dragonfish-24.04.0

Sincerely

**Comment by Supporterino** [comment]
Hi,
those metrics could not be reported because your CPU/Disk doesn't report them to TrueNAS at all that is possible. Since you are on Dragonfish you could check the internal Netdata dashboard and see if they are available then we could investigate more. I also have some disk which aren't reporting all metrics.
